require("dotenv").config();
require("./config/database");

const Category = require("./models/category");
const Item = require("./models/item");
const Customer = require("./models/customer");

(async function () {
  await Category.deleteMany({});
  const categories = await Category.create([
    { name: "Mushrooms", sortOrder: 10 },
    { name: "Produce", sortOrder: 20 },
    { name: "Seafood", sortOrder: 30 },
    { name: "Meat", sortOrder: 40 },
    { name: "Frozen", sortOrder: 50 },
    { name: "Dry Goods", sortOrder: 60 },
  ]);
  await Item.deleteMany({});
  const items = await Item.create([
    {
      name: "Chanterelles",
      category: categories[0],
      qty: 50,
      unit: "lb",
      cost: 9.5,
      price: 14.95,
    },
    {
      name: "Morels",
      category: categories[0],
      qty: 100,
      unit: "lb",
      cost: 27.0,
      price: 39.95,
    },
    {
      name: "Matsutake",
      category: categories[0],
      qty: 50,
      unit: "lb",
      cost: 35.0,
      price: 47.5,
    },
    {
      name: "Black Trumpets",
      category: categories[0],
      qty: 30,
      unit: "lb",
      cost: 6.5,
      price: 12.75,
    },
    {
      name: "Hedgehog",
      category: categories[0],
      qty: 30,
      unit: "lb",
      cost: 8.5,
      price: 13.95,
    },
    {
      name: "Yellow Foot",
      category: categories[0],
      qty: 30,
      unit: "lb",
      cost: 6.5,
      price: 12.75,
    },
    {
      name: "Lobster Mushrooms",
      category: categories[0],
      qty: 50,
      unit: "lb",
      cost: 11.5,
      price: 18.95,
    },
    {
      name: "Chicken of the Woods",
      category: categories[0],
      qty: 40,
      unit: "lb",
      cost: 7.95,
      price: 13.5,
    },
    {
      name: "Green Almonds",
      category: categories[1],
      qty: 75,
      unit: "lb",
      cost: 4.5,
      price: 8.75,
    },
    {
      name: "Blood Oranges",
      category: categories[1],
      qty: 100,
      unit: "lb",
      cost: 2.5,
      price: 4.5,
    },
    {
      name: "Dragon Fruit",
      category: categories[1],
      qty: 100,
      unit: "lb",
      cost: 3.75,
      price: 7.95,
    },
    {
      name: "Buddha Hand Citrus",
      category: categories[1],
      qty: 30,
      unit: "lb",
      cost: 5.0,
      price: 8.95,
    },
    {
      name: "Sunchokes",
      category: categories[1],
      qty: 100,
      unit: "lb",
      cost: 1.75,
      price: 6.5,
    },
    {
      name: "White Aparagus",
      category: categories[1],
      qty: 60,
      unit: "lb",
      cost: 3.5,
      price: 8.5,
    },
    {
      name: "Halibut",
      category: categories[2],
      qty: 340,
      unit: "lb",
      cost: 15.5,
      price: 25.5,
    },
    {
      name: "Quinalt Salmon",
      category: categories[2],
      qty: 150,
      unit: "lb",
      cost: 11.95,
      price: 21.95,
    },
    {
      name: "Black Cod",
      category: categories[2],
      qty: 100,
      unit: "lb",
      cost: 8.5,
      price: 16.5,
    },
    {
      name: "Rabbit",
      category: categories[3],
      qty: 30,
      unit: "lb",
      cost: 5.5,
      price: 13.95,
    },
    {
      name: "Venison",
      category: categories[3],
      qty: 50,
      unit: "lb",
      cost: 6.75,
      price: 12.5,
    },
    {
      name: "Quail",
      category: categories[3],
      qty: 25,
      unit: "lb",
      cost: 4.0,
      price: 9.95,
    },
    {
      name: "Frozen Huckleberry",
      category: categories[4],
      qty: 100,
      unit: "lb",
      cost: 5.0,
      price: 10.5,
    },
    {
      name: "Frozen White Truffles",
      category: categories[4],
      qty: 454,
      unit: "gram",
      cost: 2.5,
      price: 4.75,
    },
    {
      name: "Frozen Huatlicoche",
      category: categories[4],
      qty: 30,
      unit: "lb",
      cost: 28.95,
      price: 39.95,
    },
    {
      name: "Verjus",
      category: categories[5],
      qty: 45,
      unit: "bottle",
      cost: 6.0,
      price: 12.0,
    },
    {
      name: "Dried Heirloom Lemon",
      category: categories[5],
      qty: 1000,
      unit: "gram",
      cost: 1.0,
      price: 2.75,
    },
    {
      name: "Gluten Free Flour",
      category: categories[5],
      qty: 60,
      unit: "lb",
      cost: 4.0,
      price: 8.75,
    },
    {
      name: "Arborio Rice",
      category: categories[5],
      qty: 50,
      unit: "lb",
      cost: 7.5,
      price: 13.5,
    },
  ]);
  await Customer.deleteMany({});
  const customers = await Customer.create([
    {
      user: "649997fefba4a016758a5bbe",
      name: "Per Se",
      contactPerson: "John",
      email: "john@perse.com",
      phoneNumber: 2125551234,
    },
    {
      user: "649997fefba4a016758a5bbe",
      name: "Canlis",
      contactPerson: "Jane",
      email: "jane@canlis.com",
      phoneNumber: 3605551234,
    },
    {
      user: "649997fefba4a016758a5bbe",
      name: "Senia",
      contactPerson: "Koa",
      email: "koa@senia.com",
      phoneNumber: 8085551234,
    },
  ]);
  console.log(items);
  process.exit();
})();
